services:          #default synxtax
  frontendnginxfirst:        #naming convention for container
    build: /opt/Three-tier-docker/counter/ #location of the docker file
    ports:     #port mapping my container to host port 
      - '80:80'  
    container_name: nginxfrontendcontfirst  #providing name to container
    volumes:   #mounting persistent volume of my host to container
      - myapp:/usr/share/nginx/html/
    network_mode:   #providing network mode
        bridge
 
volumes:   #creating volume
  myapp:     